name: Beam Build Engine

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo_url }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Script Dependencies
        run: npm install @supabase/supabase-js mime-types ws node-fetch

      - name: Run Vite Build
        run: npm run build

      - name: Install Script Dependencies
        # 'ws' add kiya hai taaki Supabase client Node 20 par crash na ho
        run: npm install @supabase/supabase-js mime-types ws

      - name: Upload to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PROJECT_ID: ${{ github.event.client_payload.project_id }}
        run: |
          curl -s https://raw.githubusercontent.com/ShivaniGujjar/beam/master/.github/scripts/upload.cjs -o upload_script.cjs
          node upload_script.cjs